<a href="https://colab.research.google.com/github/Srikalyani-chemdata/sustaunable-materials-ai/blob/main/Numpy_7_7_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
nano_element = 25
single_array = np.array (nano_element)
print ("our numpy databox:", single_array)
print ("thats dimention:", single_array.ndim)

our numpy databox: 25
thats dimention: 0


In [ ]:
# 3 nano particles sizes list
nano_sizes_list = [25,45,60]
# Numpy array creating
one_d_array = np.array (nano_sizes_list)
print ("our 1d array (chemical list):",one_d_array)
print ("that's dimention:",one_d_array.ndim)

our 1d array (chemical list): [25 45 60]
that's dimention: 1


In [ ]:
# 2d array data creation
chemical_table = [
    [25,45,60],
    [30,50,75]
]
two_d_array = np.array (chemical_table)
print ("our 2d numpy table:", two_d_array)
print ("That,s dimention:", two_d_array.ndim)

our 2d numpy table: [[25 45 60]
 [30 50 75]]
That,s dimention: 2


In [ ]:
import numpy as np
#1 --Here we rae taking 1D arrys list of 4 chemicals bond lenths
bond_lengths = [1.21, 1.43, 1.54, 1.32]
chemistry_array = np.array(bond_lengths)
# first chemical index=0, 3rd chemical index=2 are taking out individually
first_chemical = chemistry_array [0]
third_chemical = chemistry_array [2]
print ("--Numpy lab: data indexing--")
print ("first chemical bond length [indexing=0]:",first_chemical)
print ("third chemical bond length [indexing=2]:", third_chemical)

--Numpy lab: data indexing--
first chemical bond length [indexing=0]: 1.21
third chemical bond length [indexing=2]: 1.54


1D-array slicing process:
Here in an array not only single value we take out, in an array if more values are present, then we cut sertain lenth of array by using slice.
ex: np.ayyay[20,30,40,50,60,70] values out of them if you want to cut some values we use (start:end) means stating value and ending value.
remember: ending value is cut value one step before its series. means: [0:3]
means ayyay slices: 0,1,2 index values(20,30,40 according to abpve data) hope its clear...

In [ ]:
import numpy as np
# Here we are taking 5 chemicals bond lengths--
bond_lengths = [1.21,1.43, 1.54, 1.32, 1.67]
chemistry_array = np.array(bond_lengths)
chemical_slice = chemistry_array[1:4]
print("--Numpy lab: data slicing--")
print("Total chemicals data:", chemistry_array)
print("Sliced data (Index 1 to 3):", chemical_slice)

--Numpy lab: data slicing--
Total chemicals data: [1.21 1.43 1.54 1.32 1.67]
Sliced data (Index 1 to 3): [1.43 1.54 1.32]


2D-array indexing:
inthis data is saved in tablar formate of rows&columns, so if you want to take out any value you need to enter perticular row& column details of that array. Remember that here also rows and columns indexing starts from "zero".

In [ ]:
import numpy as np
# -- Here we rae taking 2 rows & 3 columns chemical table formatted data--
# Row 0 = [25,45,60] batch:A
# Row 1 = [30,50,75] batch:B
# Remember: Here rows index & coumn index can starts from "Zero"
chemical_table = [
    [25,45,60],
    [30,50,75]
]
two_d_array = np.array(chemical_table)
#-- Accsessing 1st row middle element--
specific_element = two_d_array[0,1]
print("--Numpy lab:2D indexing--")
print("our 2D table:\n", two_d_array)
print("our specific value(row=0,colm=1):",specific_element)


--Numpy lab:2D indexing--
our 2D table:
 [[25 45 60]
 [30 50 75]]
our specific value(row=0,colm=1): 45


2D array slicing process:
2D slicing means cutting specif row or coumn data completely out from array.
if we give [:,0] here colon means select all rows and 0 means only first coumn. means we are taking out data of all rows 1st coumn information.

In [ ]:
import numpy as np
chemical_table = [
    [25,45,60],
    [30,50,75]
]
two_d_array = np.array(chemical_table)
first_column_slice = two_d_array[:,0]
print("--Numpy lab:2-D slicing--")
print("our 2d total table:\n", two_d_array)
print("data of sliced first column:", first_column_slice)

--Numpy lab:2-D slicing--
our 2d total table:
 [[25 45 60]
 [30 50 75]]
data of sliced first column: [25 30]


Numpy mathematical operations:

In numpy when we have thousands of data and we need o calculate any mathematicla operations like addition, substraction,multiplication we can do it for entire data at a time, its called vectorisation. we can calculate the average of all data by using np.mean() functin in numpy.

In [ ]:
import numpy as np
# In one chemical batch 4 nanoparticles sizes--
nano_sizes = [20,35,50,65]
chemistry_array = np.array(nano_sizes)
# Addition: here we are going to add 5nm to each size
increased_sizes = chemistry_array + 5
# Average\Mean calculation:
average_size = np.mean(chemistry_array)
print("--Numpy lab: Mathamatical operations---")
print("Our particles original sizes:", chemistry_array)
print("5nm added sizes:",increased_sizes)
print("Average of this batch:", average_size)

--Numpy lab: Mathamatical operations---
Our particles original sizes: [20 35 50 65]
5nm added sizes: [25 40 55 70]
Average of this batch: 42.5


PANDAS:
Pandas is a python libraty mainly used analyse big data and manipulation of data. pandas has 2 datastructures/: 1. series, 2. Dtaframe
1.Series: It contains only one column, (as like numpy 1D)  
2. Dtaframes: it contains rows & columns tablar formate data (as like np.2D table)

In [ ]:

import pandas as pd
# Three types of nanoparticles with sizes in dictionary data form--
chemical_data={
    "Nanoparticle": ["ZrO2", "TiO2", "SiO2"],
    "Size_nm" : [25, 45, 60],
    "stability": ["High", "Medium", "High"]
}
# Dta converted into pandas dataframe--
df = pd.DataFrame(chemical_data)
print("--Pandas lab: creating our first DataFrame--")
print(df)


--Pandas lab: creating our first DataFrame--
  Nanoparticle  Size_nm stability
0         ZrO2       25      High
1         TiO2       45    Medium
2         SiO2       60      High


Accessing DatFrame data:

We know that in our DataFrame data is saved in 2D form of Rows & Columns
if we want only one row/one column we use:
1. One column: df.['column_name']
2. one Row: .iloc[]
ex: df.iloc[0] indicates row in zero index.

In [ ]:
import pandas as pd
chemical_data = {
    "Nanoparticle": ["ZrO2", "TiO2", "SiO2"],
    "Size_nm": [25,45,60],
    "stability": ["High","Medium", "High"]
}
df = pd.DataFrame(chemical_data)
sizes_only = df['Size_nm']
first_row = df.iloc[0]
print("--Pandas lab: Accessing data-- ")
print("Total sizes of column:\n", sizes_only)
print("\n first chemical information (Row 0):\n", first_row)

--Pandas lab: Accessing data-- 
Total sizes of column:
 0    25
1    45
2    60
Name: Size_nm, dtype: int64

 first chemical information (Row 0):
 Nanoparticle    ZrO2
Size_nm           25
stability       High
Name: 0, dtype: object


Finding null values/missing values of data by using  a function in pandas
null values= .isnull().sum()  

In [ ]:
import pandas as pd
chemical_data = {
    "Nanoparticle": ["ZrO2", "TiO2", "SiO2", "Al2O3"],
    "Size_nm": [25, None, 45,60],
    "stability": ["High","Medium", "High", "Low"]
}
df = pd.DataFrame(chemical_data)
missing_values_count = df.isnull().sum()
print("--Pandas lab: Finding missing data--")
print("our chemical table:\n", df)
print("\n null values present in each column:\n", missing_values_count)

--Pandas lab: Finding missing data--
our chemical table:
   Nanoparticle  Size_nm stability
0         ZrO2     25.0      High
1         TiO2      NaN    Medium
2         SiO2     45.0      High
3        Al2O3     60.0       Low

 null values present in each column:
 Nanoparticle    0
Size_nm         1
stability       0
dtype: int64


Dta cleaning:

In DataFrame null value is filled by our selcted number by using a function in pandas: .fillna()
generally to fill null in apertucular row\column we take average of entire row\column of thet perticula null and fill that average\mean value in that is the best optin used by lage undustries.

In [ ]:
import pandas as pd
chemical_data = {
    "Nanoparticles": ["ZrO2","TiO2", "SiO2", "Al2O3"],
    "Size_nm": [25.0, None, 45.0, 60.0],
    "stability": ["High", "Medium", "High", "Low"]
}
df = pd.DataFrame(chemical_data)
mean_size = df['Size_nm'].mean()
df['Size_nm'] = df['Size_nm'].fillna(mean_size)
print("--Pandas lab: Data cleaning with mean--")
print("calculated mean size (mean size):", mean_size)
print("\n new chemical table after cleaning:\n", df)

--Pandas lab: Data cleaning with mean--
calculated mean size (mean size): 43.333333333333336

 new chemical table after cleaning:
   Nanoparticles    Size_nm stability
0          ZrO2  25.000000      High
1          TiO2  43.333333    Medium
2          SiO2  45.000000      High
3         Al2O3  60.000000       Low


Pandas DataFiltering:

If in our labdata thousands of chemicals are present in that we want to take only requred data by using condition is called data filtering.
codition used: Ex: df[df[Size_nm] > 30] means here we collect data of above 30nm size particles from large data.

In [ ]:
import pandas as pd
chemical_data = {
    "Nanoparticles": ["ZrO2", "TiO2", "SiO2", "Al2O3"],
    "Size_nm": [25.0, 43.33, 45.0, 60.0],
    "Stability": ["High", "Medium", "High", "Low"]
}
df = pd.DataFrame(chemical_data)
large_particles = df[df['Size_nm'] > 40]
print("Pands lab: Datafiltering")
print("Chemicals size with > 40nm:\n", large_particles)


Pands lab: Datafiltering
Chemicals size with > 40nm:
   Nanoparticles  Size_nm Stability
1          TiO2    43.33    Medium
2          SiO2    45.00      High
3         Al2O3    60.00       Low
